news/urls.py
from django.urls import path
from . import views




# app_name = 'news'

urlpatterns = [
    path('', views.news , name='news'),
    path('<int:cat_id>/' ,  views.category , name='category'),
    path('<str:wil_id>/' , views.wildetail, name='wilaya'),
    path('follow/follow/' , views.following, name='follow'),
    path('dests/dest/' , views.dest, name='destination'),
    # path('', views.CategoryView.as_view(), name='news'),
]

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path("make/", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('<int:voter_id>/voter/' , views.voted , name='voted'),
    
    
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls ),
    path('', include('news.urls')),
    path('p/polls/' , include('polls.urls')),
    path('a/agency/', include('agency.urls') ),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
'''
        months = [None, 'Janvier', 'Février' , 'Mars','Avril','Mai',
                  'Juin','Juillet','Aout','Septembre','Octobre',
                  "Novembre","Décembre"]
        d = datetime.datetime.now()
        s = d.strftime('%m')
        return f'{months[s]}'
'''
class Category(models.Model):
    category = models.CharField(max_length=255)
    created_on = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f'{self.category}'
    
    def added_on(self):
        return self.category
    
    def get_date(self):
        months  = [None,'Janvier', 'Fevrier', 'Mars','Avril',
                   'Mai','Juin','Juillet','Aout','Septembre',
                   'Octobre','Novembre','Decembre']
        month = self.post_date.month 
        #month = self.post_date.month -1
        dt = timezone.now() - self.post_date
        new = round(dt.total_seconds() / 60)
        new_dt = divmod(new, 60)
        if new_dt[0] < 1:
            return f'{new_dt[1]} minutes'
        elif new_dt[0] < 24:
            return f'{new_dt[0]} heures'
        elif new_dt[0] < 48:
            return f'un jour'
        elif new_dt[0] < 72:
            return '2 jour'

        else:
            return f'{self.post_date.day} {months[month]} {self.post_date.year}'

   
    
        
        
    
class News(models.Model):
    
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(default=timezone.now)
    
    
    def __str__(self):
        return f'{self.title} added in {self.category}'
    
    

polls/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone


q , r = divmod(34,5)
print(q)
print(r)

class Wilaya(models.Model):
    wilaya_name = models.CharField(max_length=30)
    wilaya_code = models.PositiveIntegerField()
    created_on = models.DateTimeField(default=timezone.now)
    
    def creation_month(self):
        months = [None, 'Janvier', 'Février' , 'Mars','Avril','Mai',
                  'Juin','Juillet','Aout','Septembre','Octobre',
                  "Novembre","Décembre"]
        month = self.created_on.month
        n =  timezone.now() - self.created_on
        f= n.total_seconds() / 60
        
        q ,r = divmod(f, 60)
        return f'{int(q)} heures'
        

    
    def __str__(self):
        return f'{self.wilaya_name}  code: {self.wilaya_code}'
    


class Destination(models.Model):
    destination_name = models.CharField(max_length=100)
    description = models.TextField()
    agency_name = models.ForeignKey(Wilaya, on_delete=models.CASCADE)
    super_admin = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on  = models.DateTimeField(default=timezone.now)
    destination_picture = models.ImageField(upload_to='pictures')
    
    
    def __str__(self):
        return f'{self.destination_name}'
    



class Follow(models.Model):
    wilaya_followed = models.ForeignKey(Wilaya, on_delete=models.CASCADE )
    follower = models.ForeignKey(User, on_delete=models.CASCADE)
    follow_date = models.DateTimeField(default=timezone.now)
    
    

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    def __str__(self):
        return f'{self.question_text}'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    
    def __str__(self):
        return f'{self.choice_text}'
    

class Voter(models.Model):
    question_voted = models.ForeignKey(Question , on_delete=models.CASCADE)
    voter = models.ForeignKey(User , on_delete=models.CASCADE)
    vote_date  = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.voter} voted on {self.question_voted}'

news/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render ,get_object_or_404
from . models import Category ,News
from polls.models import Wilaya , Follow , Destination
import random
from django.http import HttpResponseRedirect
from django.views.generic import ListView , DetailView
from django.contrib import messages



def following(request):
    if request.user.is_authenticated:
    
        if request.method =='POST':
            wila_id = request.POST['wilaya']
            print(wila_id)
            follow = Wilaya.objects.get(pk=wila_id)
            
            if Follow.objects.filter(wilaya_followed=follow, follower=request.user).exists():
                print("Combination exists")
                messages.info(request , 'Combination exists')
            
                
            else:
                w = Follow(wilaya_followed=follow, follower=request.user)
                w.save()
                messages.success(request, 'Congratulations , you are following this wilaya now!')
            
            return HttpResponseRedirect('/')
    else:
        messages.warning(request, 'User is not logged in ')
               
        return HttpResponseRedirect('/')
        

def dest(request):
    dests = Destination.objects.all()
    
    return render(request , 'news/destination.html' , {'dests': dests})


def wildetail(request, wil_id):
    

  
    wil = get_object_or_404(Wilaya, wilaya_name=wil_id)
    print(type(wil.id))
    wi = get_object_or_404(Wilaya, pk=wil.id)
    
    return render(request, "news/wilaya.html", {"wila": wil  , 'will': wi})


class CategoryView(ListView):
    template_name = 'news/news_list.html'
    context_object_name = 'cats'
    model = Category
    
    def get_queryset(self):
        categories = Category.objects.all()
        cats = random.sample(list(categories) ,len(categories))
        return cats
        
wila = ['Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 
 'Batna', 'Béjaïa', 'Biskra', 'Béchar', 'Blida', 'Bouira',
 'Tamanrasset', 'Tébessa', 'Tlemcen', 'Tiaret', 'Tizi Ouzou',
 'Alger', 'Djelfa', 'Jijel', 'Sétif', 'Saïda', 'Skikda', 'Sidi Bel Abbès',
 'Annaba', 'Guelma', 'Constantine', 'Médéa','Mostaganem', 'MSila',
 'Mascara', 'Ouargla', 'Oran', 'El Bayadh','Illizi',
 'Bordj Bou Arreridj', 'Boumerdès', 'El Tarf' ,'Tindouf', 'Tissemsilt', 
 'El Oued', 'Khenchela', 'Souk Ahras',
 'Tipaza', 'Mila', 'Aïn Defla', 'Naâma', 'Aïn Témouchent',
 'Ghardaïa', 'Relizane']

def news(request):
    # for i in wila :
    #     n = wila.index(i) + 1
    #     print(n)
        
    #     wil = Wilaya(wilaya_name= i  , wilaya_code= n)
    #     wil.save() 
    #     print('saved')
    
    categories = Category.objects.all()
    wils = Wilaya.objects.all()
    
    cato = random.sample(list(categories) ,len(categories))
    cats = cato[:6]
    context = { 'wilayas': wils,'categories' : categories , 'cats': cats}
    return render(request, 'news/news_list.html', context)



def category(request, cat_id):
    category = get_object_or_404(Category , pk=cat_id)
    
    context = {'category':category}
    
    return render(request, 'news/category.html' , context)

news/templates/news/category.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>category</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <style>
        *{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        div.container{
            width: 90%;
            margin: auto;
            background-color: lightblue;
            height: 100vh;
        }
        nav h1{
            text-align: center;
            font-size: 34px;
        }
        
    </style>
</head>
<body>
    <nav>
        <h1>Welcome to {{category.category|title}}</h1>
    </nav>

    <div class="container">
       

    <ul>
        {% for news in category.news_set.all %}
            <h2>{{ news.title|title}}</h2>
            <li>{{news.content }}</li>
            
        {% endfor %}
        </ul>
    </div>
    
</body>
</html>

news/templates/news/destination.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <style>
        body{
            background-color: turquoise;
        }
    </style>
</head>
<body>
    <div>
        <img src="{% static 'img/logan.jpg' %}" alt="">
    </div>
    {% for dest in dests %}
    <h2>{{ dest.destination_name|title }} </h2>
    <h3>{{dest.agency_name.wilaya_name }} </h3>
    {{dest.super_admin}}
    <img src=" {{ dest.destination_picture }}" alt="{{ dest.destination_picture }}">
    {% endfor %}
    
</body>
</html>

news/templates/news/news_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>


    <style>
        *{
            box-sizing: border-box;
            margin: 0;
        }
        body{
            background-color: tomato;
        }
        div.cats{
            display: grid;
            grid-gap:10px;
            grid-template-columns: 1fr 1fr 1fr;
            width : 100%;
        }
        div.cats .cat{
            background-color: lightblue;
            height: 300px;

        }
        h1{
            font-size: 30px;
            color: white;
            text-align: center;
            text-transform: capitalize;
        }
        h3{
            text-align: center;
            

        }
        @media screen and (max-width: 600px) {
            div.cats{
                width: 90%;
                display: grid;
                height: auto;
                grid-template-columns: 1fr;
                margin-left: 5%;
            }
            body{
                background-color: lightblue;
            }
            div.cats .cat{
                background-color: tomato;
            }
            
        
          }
    </style>
    
</head>
<body>
    <div style="font-size: 23px; background-color:white; text-align:center">
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </div>
    <section>
        <div class="container">
            <div class="header">
                <h1>Welcome to Rahalet</h1>
                <h3>book your trip from here</h3>
                <a href="{% url 'polls:index' %}">polls</a>
                
                {% if request.user.is_authenticated and request.user.is_staff and request.user.username == 'hakim'%}
                
                <a href="{% url 'admin:index' %}">admin</a>
                {%  endif %}
                <a href="{% url 'polls:voted' voted}"> voter</a>
                
            </div>
            <div class="cats">
                {% for wil in wilayas %}

                <div class="cat">
                    <h2> <a href="{% url 'wilaya' wil.wilaya_name %}">{{wil.wilaya_name|title }}</a> </h2>
                    <span>{{wil.wilaya_code}}</span>
                    <h3>{{wil.created_on}}</h3>
                    <h3>Il y a {{wil.creation_month }}</h3>
                    

                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    
</body>
</html>

news/templates/news/wilaya.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

</head>
<body>
    <div>
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </div>
    <h2>{{wila.wilaya_name}}</h2>
    <h3>the id is : {{wila.id}}</h3>
    <form action="{% url 'follow' %}" method="post">
        {% csrf_token %}

        <input type="hidden" name="wilaya" value ="{{wila.id}}">

        <BUTTon>fOLLOW</BUTTon>

    </form>
    {% for destination in will.destination_set.all %}
   <h3> {{destination.agency_name}}</h3>

    {% endfor %}


    
</body>
</html>